name: Build docker images

on:
  # repository_dispatch:
  #   types:
  #     - base-image-update
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "Dockerfile"
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/terraform-azure-cli

jobs:
  docker-buildx:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set versions
        id: version
        run: | 
          echo "terraform_version=$(jq -r '.terraform_version' versions.json)" >> $GITHUB_OUTPUT
          echo "azure_cli_version=$(jq -r '.azure_cli_version' versions.json)" >> $GITHUB_OUTPUT

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}

      - name: Login to Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          platforms: |
            linux/amd64
            linux/arm/v6
            linux/arm/v7
            linux/arm64/v8
          build-args: | 
            TERRAFORM_VERSION=${{ steps.terraform_version.outputs.terraform_version }}
            AZURE_CLI_VERSION=${{ steps.azure_cli_version.outputs.azure_cli_version }}
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:terraform-${{ steps.terraform_version.outputs.terraform_version }}-azure-cli-${{ steps.azure_cli_version.outputs.azure_cli_version }}
