name: Container Registry Cleanup

permissions:
  contents: read
  packages: write

on:
  workflow_dispatch:
  schedule:
    - cron: "30 2 * * mon"

env:
  IMAGE_NAME: terraform-azure-cli

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      #   - uses: "tweedegolf/cleanup-images-action@main"
      #     with:
      #       package: debian
      #       filters: "^nightly-\\d{2}-\\d{2}-\\d{4}$"
      #       keep_n: 5
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: user
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: ${{ env.IMAGE_NAME }}
          tag-selection: untagged
          cut-off: 1m
          dry-run: false
